export enum LandingFeatureIconsState {
  SIZE_24_MEETING = 'SIZE_24_MEETING',
  SIZE_24_EVENT = 'SIZE_24_EVENT',
  SIZE_24_MOODTRACKER = 'SIZE_24_MOODTRACKER',
  SIZE_24_CALENDAR = 'SIZE_24_CALENDAR',
  SIZE_24_MEETING_WHITE = 'SIZE_24_MEETING_WHITE',
  SIZE_24_EVENT_WHITE = 'SIZE_24_EVENT_WHITE',
  SIZE_24_MOODTRACKER_WHITE = 'SIZE_24_MOODTRACKER_WHITE',
  SIZE_24_CALENDAR_WHITE = 'SIZE_24_CALENDAR_WHITE',
  SIZE_62_MEETING = 'SIZE_62_MEETING',
  SIZE_62_EVENT = 'SIZE_62_EVENT',
  SIZE_62_MOODTRACKER = 'SIZE_62_MOODTRACKER',
}
