export enum FeaturedFileIconsState {
  SIZE_24_AI_MANAGER_FILE = 'SIZE_24_AI_MANAGER_FILE',
  SIZE_20_AI_MANAGER_FILE = 'SIZE_20_AI_MANAGER_FILE',
  SIZE_16_AI_MANAGER_FILE = 'SIZE_16_AI_MANAGER_FILE',
  SIZE_24_SNS_ASSISTANT_FILE = 'SIZE_24_SNS_ASSISTANT_FILE',
  SIZE_20_SNS_ASSISTANT_FILE = 'SIZE_20_SNS_ASSISTANT_FILE',
  SIZE_16_SNS_ASSISTANT_FILE = 'SIZE_16_SNS_ASSISTANT_FILE',
  SIZE_24_TEAM_MOOD_FILE = 'SIZE_24_TEAM_MOOD_FILE',
  SIZE_20_TEAM_MOOD_FILE = 'SIZE_20_TEAM_MOOD_FILE',
  SIZE_16_TEAM_MOOD_FILE = 'SIZE_16_TEAM_MOOD_FILE',
}
