export enum IndividualIconsState {
  CONGRATULATE_SIGN_UP = 'CONGRATULATE_SIGN_UP',
  WARNING = 'WARNING',
  UNDER_ARROW = 'UNDER_ARROW',
  SEARCH = 'SEARCH',
  CALENDAR_SIZE_18 = 'CALENDAR_SIZE_18',
  CALENDAR_SIZE_16 = 'CALENDAR_SIZE_16',
  UPLOAD = 'UPLOAD',
  GROUP = 'GROUP',
  EMAIL = 'EMAIL',
}
