export enum IndividualIconsState {
  CONGRATULATE_SIGN_UP = 'CONGRATULATE_SIGN_UP',
  WARNING = 'WARNING',
  UNDER_ARROW = 'UNDER_ARROW',
  SEARCH = 'SEARCH',
  CALENDAR = 'CALENDAR',
  UPLOAD = 'UPLOAD',
  GROUP = 'GROUP',
  EMAIL = 'EMAIL',
}
