export enum LeftGnbIconsState {
  HOME = 'HOME',
  HOME_DISABLED = 'HOME_DISABLED',
  AI_MANAGER = 'AI_MANAGER',
  AI_MANAGER_DISABLED = 'AI_MANAGER_DISABLED',
  MY_CALENDAR = 'MY_CALENDAR',
  MY_CALENDAR_DISABLED = 'MY_CALENDAR_DISABLED',
  SNS_ASSISTANT = 'SNS_ASSISTANT',
  SNS_ASSISTANT_DISABLED = 'SNS_ASSISTANT_DISABLED',
  TEAM_MOOD_TRACKER = 'TEAM_MOOD_TRACKER',
  TEAM_MOOD_TRACKER_DISABLED = 'TEAM_MOOD_TRACKER_DISABLED',
  RECENT_FILE = 'RECENT_FILE',
}
