export const API_ERROR_CODES = {
  MEMBER: {
    NOT_FOUND: 'MEMBER4001',
    REFRESH_TOKEN_NOT_EQUAL: 'MEMBER4002',
    NO_AUTHORITY: 'MEMBER4003',
    ALREADY_EXISTS: 'MEMBER4004',
    USERNAME_NOT_FOUND: 'MEMBER4005',
    PASSWORD_NOT_MATCH: 'MEMBER4006',
  },
  WORKSPACE: {
    NOT_FOUND: 'WORKSPACE4001',
    MODIFY_NOT_ALLOWED: 'WORKSPACE4002',
    INVITATION_NOT_FOUND: 'WORKSPACE4003',
    EMAIL_MISMATCH: 'WORKSPACE4004',
    ALREADY_ACCEPTED: 'WORKSPACE4005',
    NOT_BELONG: 'WORKSPACE4006',
    CREATOR_NOT_FOUND: 'WORKSPACE4007',
  },
  USER_WORKSPACE: {
    NOT_FOUND: 'USERWORKSPACE4001',
  },
  MEETING: {
    NOT_FOUND: 'MEETING4001',
    FILE_NOT_FOUND: 'MEETING4002',
  },
  AUTHORIZATION: {
    EXCEPTION: 'AUTHORIZATION4001',
    JWT_ACCESS_EXPIRED: 'AUTHORIZATION4002',
    JWT_REFRESH_EXPIRED: 'AUTHORIZATION4003',
    LOGOUT_USER: 'AUTHORIZATION4004',
    JWT_NOT_RECEIVED: 'AUTHORIZATION4005',
    JWT_OUT_OF_FORM: 'AUTHORIZATION4006',
  },
  MOOD_TRACKER: {
    NOT_FOUND: 'MOODTRACKER4001',
    MODIFY_NOT_ALLOWED: 'MOODTRACKER4002',
    SURVEY_QUESTION_NOT_FOUND: 'MOODTRACKER4003',
    SURVEY_ANSWER_REQUIRED: 'MOODTRACKER4004',
    NOT_FINISHED: 'MOODTRACKER4005',
    ACCESS_DENIED: 'MOODTRACKER4006',
  },
  MAIL: {
    SEND_FAIL: 'MAIL500',
  },
  SNS_EVENT: {
    NOT_FOUND: 'SNSEVENT4001',
    LINK_NOT_FOUND: 'SNS_EVENT4002',
    INSTAGRAM_API_ERROR: 'SNS_EVENT4003',
    INSTAGRAM_API_NO_MEDIA: 'SNS_EVENT4004',
    INSTAGRAM_API_NO_COMMENT: 'SNS_EVENT4005',
    NO_ACCESS_TOKEN: 'SNS_EVENT4006',
    NO_AUTHORITY: 'SNS_EVENT4007',
  },
} as const;
