export enum CheckboxIconsState {
  CIRCLE_CHECKBOX_ENABLED = 'CIRCLE_CHECKBOX_ENABLED',
  CIRCLE_CHECKBOX_DISABLED = 'CIRCLE_CHECKBOX_DISABLED',
  SQUARE_CHECKBOX_ENABLED = 'SQUARE_CHECKBOX_ENABLED',
  SQUARE_CHECKBOX_DISABLED = 'SQUARE_CHECKBOX_DISABLED',
  SIZE_24_SQUARE_CHECKBOX_ENABLED = 'SIZE_24_SQUARE_CHECKBOX_ENABLED',
  SIZE_24_SQUARE_CHECKBOX_DISABLED = 'SIZE_24_SQUARE_CHECKBOX_DISABLED',
}
